# Generated by Django 5.1.3 on 2024-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_options_resume_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.JSONField(default=list),
        ),
    ]
